<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpotifyRecom.Data\SpotifyRecom.Data.csproj" />
    <ProjectReference Include="..\SpotifyRecom.Model\SpotifyRecom.Model.csproj" />
  </ItemGroup>

</Project>
