// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpotifyRecom.Data;

#nullable disable

namespace SpotifyRecom.Data.Migrations
{
    [DbContext(typeof(SpotifyRecomContext))]
    partial class SpotifyRecomContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AlbumArtista", b =>
                {
                    b.Property<int>("AlbunsIdAlbum")
                        .HasColumnType("int");

                    b.Property<int>("ArtistasIdArtista")
                        .HasColumnType("int");

                    b.HasKey("AlbunsIdAlbum", "ArtistasIdArtista");

                    b.HasIndex("ArtistasIdArtista");

                    b.ToTable("AlbumArtista");
                });

            modelBuilder.Entity("ArtistaGenero", b =>
                {
                    b.Property<int>("ArtistasIdArtista")
                        .HasColumnType("int");

                    b.Property<int>("GenerosArtistaIdGenero")
                        .HasColumnType("int");

                    b.HasKey("ArtistasIdArtista", "GenerosArtistaIdGenero");

                    b.HasIndex("GenerosArtistaIdGenero");

                    b.ToTable("ArtistaGenero");
                });

            modelBuilder.Entity("ArtistaMidia", b =>
                {
                    b.Property<int>("ArtistasIdArtista")
                        .HasColumnType("int");

                    b.Property<int>("MidiasIdMidia")
                        .HasColumnType("int");

                    b.HasKey("ArtistasIdArtista", "MidiasIdMidia");

                    b.HasIndex("MidiasIdMidia");

                    b.ToTable("ArtistaMidia");
                });

            modelBuilder.Entity("BibliotecaMidia", b =>
                {
                    b.Property<int>("BibliotecasIdBiblioteca")
                        .HasColumnType("int");

                    b.Property<int>("MidiasIdMidia")
                        .HasColumnType("int");

                    b.HasKey("BibliotecasIdBiblioteca", "MidiasIdMidia");

                    b.HasIndex("MidiasIdMidia");

                    b.ToTable("BibliotecaMidia");
                });

            modelBuilder.Entity("BibliotecaPlaylist", b =>
                {
                    b.Property<int>("BibliotecasIdBiblioteca")
                        .HasColumnType("int");

                    b.Property<int>("PlaylistsIdPlaylist")
                        .HasColumnType("int");

                    b.HasKey("BibliotecasIdBiblioteca", "PlaylistsIdPlaylist");

                    b.HasIndex("PlaylistsIdPlaylist");

                    b.ToTable("BibliotecaPlaylist");
                });

            modelBuilder.Entity("GeneroMidia", b =>
                {
                    b.Property<int>("GenerosMidiaIdGenero")
                        .HasColumnType("int");

                    b.Property<int>("MidiasIdMidia")
                        .HasColumnType("int");

                    b.HasKey("GenerosMidiaIdGenero", "MidiasIdMidia");

                    b.HasIndex("MidiasIdMidia");

                    b.ToTable("GeneroMidia");
                });

            modelBuilder.Entity("MidiaPlaylist", b =>
                {
                    b.Property<int>("MidiasIdMidia")
                        .HasColumnType("int");

                    b.Property<int>("PlaylistsIdPlaylist")
                        .HasColumnType("int");

                    b.HasKey("MidiasIdMidia", "PlaylistsIdPlaylist");

                    b.HasIndex("PlaylistsIdPlaylist");

                    b.ToTable("MidiaPlaylist");
                });

            modelBuilder.Entity("SpotifyRecom.Model.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAlbum"));

                    b.Property<int>("AnoLancamento")
                        .HasColumnType("int");

                    b.Property<int>("ArtistaId")
                        .HasColumnType("int");

                    b.Property<int>("MidiaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdAlbum");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("SpotifyRecom.Model.Artista", b =>
                {
                    b.Property<int>("IdArtista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdArtista"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdArtista");

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("SpotifyRecom.Model.ArtistaSeguido", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("ArtistaId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "ArtistaId");

                    b.HasIndex("ArtistaId");

                    b.ToTable("ArtistasSeguidos", (string)null);
                });

            modelBuilder.Entity("SpotifyRecom.Model.Biblioteca", b =>
                {
                    b.Property<int>("IdBiblioteca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdBiblioteca"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdBiblioteca");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Bibliotecas");
                });

            modelBuilder.Entity("SpotifyRecom.Model.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdGenero"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdGenero");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("SpotifyRecom.Model.Midia", b =>
                {
                    b.Property<int>("IdMidia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMidia"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("ArtistaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time(6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdMidia");

                    b.HasIndex("AlbumId");

                    b.ToTable("Midias");
                });

            modelBuilder.Entity("SpotifyRecom.Model.MusicaCurtida", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("MidiaId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "MidiaId");

                    b.HasIndex("MidiaId");

                    b.ToTable("MusicasCurtidas", (string)null);
                });

            modelBuilder.Entity("SpotifyRecom.Model.MusicaPlaylist", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("MidiaId")
                        .HasColumnType("int");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "MidiaId", "PlaylistId");

                    b.HasIndex("MidiaId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("MusicasPlaylists", (string)null);
                });

            modelBuilder.Entity("SpotifyRecom.Model.Plano", b =>
                {
                    b.Property<int>("IdPlano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlano"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdPlano");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("SpotifyRecom.Model.Playlist", b =>
                {
                    b.Property<int>("IdPlaylist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlaylist"));

                    b.Property<string>("NomePlaylist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdPlaylist");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("SpotifyRecom.Model.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlanoId")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.HasIndex("PlanoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AlbumArtista", b =>
                {
                    b.HasOne("SpotifyRecom.Model.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbunsIdAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyRecom.Model.Artista", null)
                        .WithMany()
                        .HasForeignKey("ArtistasIdArtista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtistaGenero", b =>
                {
                    b.HasOne("SpotifyRecom.Model.Artista", null)
                        .WithMany()
                        .HasForeignKey("ArtistasIdArtista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyRecom.Model.Genero", null)
                        .WithMany()
                        .HasForeignKey("GenerosArtistaIdGenero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtistaMidia", b =>
                {
                    b.HasOne("SpotifyRecom.Model.Artista", null)
                        .WithMany()
                        .HasForeignKey("ArtistasIdArtista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyRecom.Model.Midia", null)
                        .WithMany()
                        .HasForeignKey("MidiasIdMidia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BibliotecaMidia", b =>
                {
                    b.HasOne("SpotifyRecom.Model.Biblioteca", null)
                        .WithMany()
                        .HasForeignKey("BibliotecasIdBiblioteca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyRecom.Model.Midia", null)
                        .WithMany()
                        .HasForeignKey("MidiasIdMidia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BibliotecaPlaylist", b =>
                {
                    b.HasOne("SpotifyRecom.Model.Biblioteca", null)
                        .WithMany()
                        .HasForeignKey("BibliotecasIdBiblioteca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyRecom.Model.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsIdPlaylist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeneroMidia", b =>
                {
                    b.HasOne("SpotifyRecom.Model.Genero", null)
                        .WithMany()
                        .HasForeignKey("GenerosMidiaIdGenero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyRecom.Model.Midia", null)
                        .WithMany()
                        .HasForeignKey("MidiasIdMidia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MidiaPlaylist", b =>
                {
                    b.HasOne("SpotifyRecom.Model.Midia", null)
                        .WithMany()
                        .HasForeignKey("MidiasIdMidia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyRecom.Model.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsIdPlaylist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpotifyRecom.Model.ArtistaSeguido", b =>
                {
                    b.HasOne("SpotifyRecom.Model.Artista", "Artista")
                        .WithMany()
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyRecom.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SpotifyRecom.Model.Biblioteca", b =>
                {
                    b.HasOne("SpotifyRecom.Model.Usuario", "Usuario")
                        .WithOne("biblioteca")
                        .HasForeignKey("SpotifyRecom.Model.Biblioteca", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SpotifyRecom.Model.Midia", b =>
                {
                    b.HasOne("SpotifyRecom.Model.Album", "Album")
                        .WithMany("Midias")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("SpotifyRecom.Model.MusicaCurtida", b =>
                {
                    b.HasOne("SpotifyRecom.Model.Midia", "Midia")
                        .WithMany()
                        .HasForeignKey("MidiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyRecom.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Midia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SpotifyRecom.Model.MusicaPlaylist", b =>
                {
                    b.HasOne("SpotifyRecom.Model.Midia", "Midia")
                        .WithMany()
                        .HasForeignKey("MidiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyRecom.Model.Playlist", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyRecom.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Midia");

                    b.Navigation("Playlist");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SpotifyRecom.Model.Playlist", b =>
                {
                    b.HasOne("SpotifyRecom.Model.Usuario", "Usuario")
                        .WithMany("Playlists")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SpotifyRecom.Model.Usuario", b =>
                {
                    b.HasOne("SpotifyRecom.Model.Plano", "Plano")
                        .WithMany("Usuarios")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("SpotifyRecom.Model.Album", b =>
                {
                    b.Navigation("Midias");
                });

            modelBuilder.Entity("SpotifyRecom.Model.Plano", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SpotifyRecom.Model.Usuario", b =>
                {
                    b.Navigation("Playlists");

                    b.Navigation("biblioteca")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
