<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SpotifyRecom.Model\SpotifyRecom.Model.csproj" />
    <ProjectReference Include="..\SpotifyRecom.Data\SpotifyRecom.Data.csproj" />
    <Compile Include="..\SpotifyRecom.Model\Menu.cs" Link="Menu.cs" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
